### ISSUE TITLE
diphthong spelling

### ISSUE THREAD

**Issue by martino-vic** [pavelsof/ipatok#2]
Hey, thank you for the package it works really well, I love it. This issue doesn't affect its functionally at all, just wanted to point out that it's spelled *diphthong* (not diphtong). Have a nice day.

**Comment by pavelsof** [comment]
Thank you very much for the nice words! I am happy that you find the package useful :)

How did I manage to never notice this spelling blunder, I have no clue.. I will take care of it, thank you for pointing it out! :)
